import AppKit
import ClipStackCore

/// Polls the general pasteboard (macOS offers no push notification for it)
/// and appends new content to the history store.
final class ClipboardMonitor {
    /// Marker type we attach to our own writes so restores are not re-captured
    /// as brand-new entries (the item is promoted explicitly instead).
    static let selfMarker = NSPasteboard.PasteboardType("com.james.clipstack.self")

    /// Conventional types (see nspasteboard.org) that well-behaved apps attach
    /// to sensitive or ephemeral content — password managers, auto-generated
    /// data, etc. We never record those.
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private let store: HistoryStore
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Payload caps: anything bigger is ignored rather than bloating the store.
    private let maxTextBytes = 5_000_000
    private let maxRichFlavorBytes = 2_000_000
    private let maxImageBytes = 40_000_000

    var isPaused = false {
        didSet {
            // Skip whatever was copied while paused.
            if !isPaused { lastChangeCount = pasteboard.changeCount }
        }
    }

    init(store: HistoryStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        // 0.25s keeps rapid sequential copies (e.g. scripted `pbcopy` bursts
        // spaced 1s apart) reliably captured while staying negligible on CPU.
        let t = Timer(timeInterval: 0.25, repeats: true) { [weak self] _ in self?.tick() }
        t.tolerance = 0.05
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    private func tick() {
        guard !isPaused else { return }
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        capture()
    }

    private func capture() {
        let types = pasteboard.types ?? []
        guard !types.contains(Self.selfMarker) else { return }
        guard !types.contains(where: { Self.skipTypes.contains($0) }) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        // Priority: file URLs > image > text. (Finder copies carry an icon
        // image too; browser image copies carry the source URL as text.)
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            store.add(ClipItem(
                kind: .file,
                contentHash: ClipItem.hashOfFiles(paths),
                plainText: paths.joined(separator: "\n"),
                fileURLs: paths,
                sourceApp: source,
                byteSize: paths.joined().utf8.count
            ))
            return
        }

        if let (png, width, height) = readImageAsPNG() {
            guard png.count <= maxImageBytes else { return }
            let hash = ClipItem.hashOfImage(png)
            if store.promoteIfExists(hash: hash) { return }
            guard let fileName = try? store.storeImagePNG(png) else { return }
            store.add(ClipItem(
                kind: .image,
                contentHash: hash,
                imageFileName: fileName,
                imagePixelWidth: width,
                imagePixelHeight: height,
                sourceApp: source,
                byteSize: png.count
            ))
            return
        }

        if let text = pasteboard.string(forType: .string) {
            let bytes = text.utf8.count
            guard bytes > 0, bytes <= maxTextBytes else { return }
            guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
            var rtf = pasteboard.data(forType: .rtf)
            var html = pasteboard.data(forType: .html)
            if let r = rtf, r.count > maxRichFlavorBytes { rtf = nil }
            if let h = html, h.count > maxRichFlavorBytes { html = nil }
            store.add(ClipItem(
                kind: .text,
                contentHash: ClipItem.hashOfText(text),
                plainText: text,
                rtfData: rtf,
                htmlData: html,
                sourceApp: source,
                byteSize: bytes
            ))
        }
    }

    /// Normalizes whatever bitmap flavor is on the pasteboard to PNG bytes.
    private func readImageAsPNG() -> (Data, Int, Int)? {
        if let data = pasteboard.data(forType: .png), let rep = NSBitmapImageRep(data: data) {
            return (data, rep.pixelsWide, rep.pixelsHigh)
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return (png, rep.pixelsWide, rep.pixelsHigh)
        }
        return nil
    }
}
